using HrSystem.Application.OrgUnits.Queries;
using HrSystem.Domain.Abstractions;
using HrSystem.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace HrSystem.Infrastructure.Persistence;

public class HrSystemDbContext : DbContext
{
    public HrSystemDbContext(DbContextOptions<HrSystemDbContext> options)
        : base(options) { }

    public DbSet<Employee> Employees => Set<Employee>();
    public DbSet<OrgUnit> OrgUnits => Set<OrgUnit>();
    public DbSet<OrgType> OrgTypes => Set<OrgType>();
    public DbSet<LeaveRequest> LeaveRequests => Set<LeaveRequest>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Apply all IEntityTypeConfiguration<T> in this assembly
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(HrSystemDbContext).Assembly);

        // Register keyless projections used by raw SQL queries
        // OrgUnitFlat is a read-only projection mapped via FromSql; it has no key and no backing table/view
        modelBuilder
            .Entity<OrgUnitFlat>(eb =>
            {
                eb.HasNoKey();
                // Prevent migrations from trying to create a table/view for this type
                eb.ToView((string?)null);
                // Npgsql maps int[] automatically; specify explicitly for clarity
                eb.Property(e => e.Path).HasColumnType("integer[]");
            });


        // Ensure int PKs are generated by the database
        foreach (var et in modelBuilder.Model.GetEntityTypes())
        {
            if (typeof(BaseEntity).IsAssignableFrom(et.ClrType))
            {
                modelBuilder
                    .Entity(et.ClrType)
                    .Property<int>(nameof(BaseEntity.Id))
                    .ValueGeneratedOnAdd();
            }
        }
    }

    public override int SaveChanges()
    {
        ApplyAuditTimestamps();
        return base.SaveChanges();
    }

    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        ApplyAuditTimestamps();
        return await base.SaveChangesAsync(cancellationToken);
    }

    private void ApplyAuditTimestamps()
    {
        var utcNow = DateTime.UtcNow;
        foreach (var entry in ChangeTracker.Entries<BaseEntity>())
        {
            if (entry.State == EntityState.Modified)
            {
                entry.Property(e => e.UpdatedDate).CurrentValue = utcNow;
            }
            else if (entry.State == EntityState.Added)
            {
                if (entry.Entity.CreatedDate == default)
                    entry.Property(e => e.CreatedDate).CurrentValue = utcNow;
            }
        }
    }
}
